=== EduCaballero/LLMM/practica14_DTD/public_html/ex03.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT pelicula (titulo, direccion, anyo, plot, genero)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT direccion (director+)>
<!ELEMENT director (#PCDATA)>
<!ELEMENT anyo (#PCDATA)>
<!ELEMENT plot (protagonista+|tematica+)>
<!ELEMENT protagonista (#PCDATA)>
<!ELEMENT tematica (#PCDATA)>
<!ELEMENT genero EMPTY>
<!ATTLIST genero tipo (drama|comedia|documental|terror) #REQUIRED>

=== EduCaballero/LLMM/practica14_DTD/public_html/ex03.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 4.	Crea un documento XML que contenga información sobre una película. Crea el DTD asociado que valide que el XML contiene los siguientes elementos:
o	Título(obligatorio y no se puede repetir)
o	Director (obligatorio y pueden haber uno o más)
o	Año (obligatorio y solo puede haber uno)
o	Elemento protagonista o bien temática
	Protagonista ( pueden haber uno o más protagonistas) 
	Temática ( pueden haber uno o más protagonistas)
o	Género ha de ser un tag vacío.
	Ha de contener un atributo tipo (obligatorio y solo puede ser: “drama”, “comedia”, “documental”, “terror”, “thriller” o ”humor”)


-->
<!DOCTYPE pelicula SYSTEM "ex03.dtd">
<pelicula>
    <titulo></titulo>
    <direccion>
        <director></director>
        <director></director>
    </direccion>
    <anyo></anyo>
    <plot>
        <protagonista></protagonista>
        <protagonista></protagonista>
    </plot>
    <genero tipo="comedia"/>
</pelicula>
