=== EduCaballero/LLMM/practica15_XSD/ejemplo/ejemploXSD.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    <xs:element name="sms" >
        <xs:complexType>
            <xs:sequence>
                <xs:element name="from">
                    <xs:complexType mixed="true">
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string"/>
                        </xs:sequence>
                        <xs:attribute name="amigo" >
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="si" />
                                    <xs:enumeration value="no" /> 
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
                <xs:element name="to">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string"
                                        minOccurs="0" maxOccurs="unbounded" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="texto" type="xs:string" />
                <xs:element name="fecha">
                    <xs:complexType mixed="true">
                        <xs:attribute name="hora" type="xs:time" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== EduCaballero/LLMM/practica15_XSD/ejemplo/ejemploXSD.xml
<?xml version="1.0" encoding="UTF-8"?>
<sms xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
 xsi:noNamespaceSchemaLocation="ejemploXSD.xsd">
     <from amigo="si">
         <nombre>Pepe</nombre>
     </from>
     <to>
         <nombre>Juan</nombre>
         <nombre>Maria</nombre>
     </to>
     <texto>Terminasteis los ejercicios de DTD?</texto>
     <fecha hora="18:00:00">29:03:2015</fecha>
</sms>
