=== EduCaballero/LLMM/practica16Sintesis/sintesis.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<!--
    TODO define vocabulary identification data
    PUBLIC ID  : -//vendor//vocabulary//EN
    SYSTEM ID  : http://server/path/__NAME__
-->

<!-- TODO define your own vocabulary/syntax. Example follows:  -->
<!ELEMENT equipos (equipo+)>
<!ATTLIST equipos xmlns:xsi CDATA #REQUIRED>
<!ATTLIST equipos xsi:noNamespaceSchemaLocation CDATA #REQUIRED>

<!ELEMENT equipo (patrocodinadores?, eventosParticipado?, nombreEq, competiciones, trabajo, exitos, integrantes)>
<!ELEMENT patrocodinadores (patrocinador+)>
<!ATTLIST patrocodinadores fecha CDATA #REQUIRED>
<!ELEMENT patrocinador (#PCDATA)>

<!ELEMENT eventosParticipado (#PCDATA)>

<!ELEMENT nombreEq (#PCDATA)>

<!ELEMENT competiciones (competicion*)>
<!ELEMENT competicion (#PCDATA)>


<!ELEMENT trabajo EMPTY>
<!ATTLIST trabajo tipo CDATA #REQUIRED>

<!ELEMENT exitos (anyos)>
<!ELEMENT anyos (anyo*)>
<!ELEMENT anyo (resultado*)>
<!ATTLIST anyo num CDATA #REQUIRED>

<!ELEMENT resultado EMPTY>
<!ATTLIST resultado igual (exito | fracaso) #REQUIRED>

<!ELEMENT integrantes (integrante+)>
<!ELEMENT integrante (nombre, apellido, cargo+, fechaNac, rutaImg*, ultHoraPart, ultFechaEmp, estadisticas?)>
<!ATTLIST integrante nacionalidad (francesa | italiana | eterniana | marciana) #REQUIRED>

<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellido (#PCDATA)>
<!ELEMENT cargo (#PCDATA)>
<!ELEMENT fechaNac (#PCDATA)>
<!ELEMENT rutaImg (#PCDATA)>
<!ATTLIST rutaImg extension (jpg | png | gif) #REQUIRED>
<!ELEMENT ultHoraPart (#PCDATA)>
<!ELEMENT ultFechaEmp (#PCDATA)>
<!ELEMENT estadisticas (goles*, programas*, minions*, golpes*)>
<!ELEMENT goles EMPTY>
<!ATTLIST goles marcados CDATA #REQUIRED>
<!ELEMENT programas EMPTY>
<!ATTLIST programas realizados CDATA #REQUIRED>
<!ELEMENT minions EMPTY>
<!ATTLIST minions eliminados CDATA #REQUIRED>
<!ELEMENT golpes EMPTY>
<!ATTLIST golpes dados CDATA #IMPLIED recibidos CDATA #IMPLIED>

=== EduCaballero/LLMM/practica16Sintesis/examen/sintesis.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<!DOCTYPE equipos SYSTEM "sintesis.dtd">
<equipos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="sintesis.xsd">
    <equipo>
        <nombreEq></nombreEq>
        <trabajo tipo="desarrollo"/>
        <exitos>
            <anyos>
                <anyo num="1999">
                    <resultado igual="exito"/>
                    <resultado igual="fracaso"/>
                    <resultado igual="exito"/>
                    <resultado igual="exito"/>
                </anyo>
                <anyo num="2000">
                    <resultado igual="fracaso"/>
                    <resultado igual="fracaso"/>
                    <resultado igual="exito"/>
                    <resultado igual="exito"/>
                </anyo>
            </anyos>
        </exitos>
        <integrantes>
            <integrante>
                <nombre>pepe</nombre>
                <apellido>perez</apellido>
                <cargo>ejecutivo</cargo>
                <fechaNac>1986-10-21</fechaNac>
                <rutaImg extension="jpg">c:/olakase</rutaImg>
                <ultHoraPart>18:00:00</ultHoraPart>
                <ultFechaEmp>2017-06-03</ultFechaEmp>
                <estadisticas>
                    <goles marcados="100"/>
                    <minions eliminados="50"/>
                </estadisticas>
            </integrante>
            <integrante>
                <nombre>pepito</nombre>
                <apellido>peraz</apellido>
                <cargo>curro</cargo>
                <fechaNac>1986-10-20</fechaNac>
                <ultHoraPart>18:00:00</ultHoraPart>
                <ultFechaEmp>2017-06-03</ultFechaEmp>
                <estadisticas>
                    <goles marcados="100"/>
                    <minions eliminados="50"/>
                </estadisticas>
            </integrante>
        </integrantes>
    </equipo>
</equipos>

=== EduCaballero/LLMM/practica16Sintesis/sintesis.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<!DOCTYPE equipos SYSTEM "sintesis.dtd">
<equipos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="sintesis.xsd">
    <equipo>
        <patrocodinadores fecha="2017-06-06">
            <patrocinador>patro</patrocinador>
            <patrocinador>patroci</patrocinador>
        </patrocodinadores>
        <eventosParticipado>muchos</eventosParticipado>
        <nombreEq>EquipoUno</nombreEq>
        <competiciones>
            <competicion>ligaCatalana</competicion>
        </competiciones>
        <trabajo tipo="desarrollo"/>
        <exitos>
            <anyos>
                <anyo num="1999">
                    <resultado igual="exito"/>
                    <resultado igual="fracaso"/>
                    <resultado igual="exito"/>
                    <resultado igual="exito"/>
                </anyo>
                <anyo num="2000">
                    <resultado igual="fracaso"/>
                    <resultado igual="fracaso"/>
                    <resultado igual="exito"/>
                    <resultado igual="exito"/>
                </anyo>
            </anyos>
        </exitos>
        <integrantes>
            <integrante nacionalidad="francesa"> <!--nacionalidad="francesa" -->
                <nombre>pepe</nombre>
                <apellido>perez</apellido>
                <cargo>ejecutivo</cargo>
                <fechaNac>1986-10-21</fechaNac>
                <rutaImg extension="jpg">c:/olakase</rutaImg>
                <ultHoraPart>18:00:00</ultHoraPart>
                <ultFechaEmp>2017-06-03</ultFechaEmp>
                <estadisticas>
                    <goles marcados="100"/>
                    <minions eliminados="50"/>
                </estadisticas>
            </integrante>
            <integrante nacionalidad="marciana"> <!--nacionalidad="marciana" -->
                <nombre>pepito</nombre>
                <apellido>peraz</apellido>
                <cargo>curro</cargo>
                <fechaNac>1986-10-20</fechaNac>
                <ultHoraPart>18:00:00</ultHoraPart>
                <ultFechaEmp>2017-06-03</ultFechaEmp>
                <estadisticas>
                    <goles marcados="100"/>
                    <minions eliminados="50"/>
                </estadisticas>
            </integrante>
        </integrantes>
    </equipo>
    <equipo>
        <patrocodinadores fecha="2017-05-06">
            <patrocinador>patron</patrocinador>
            <patrocinador>patrocin</patrocinador>
        </patrocodinadores>
        <eventosParticipado>muchos</eventosParticipado>
        <nombreEq>equipoDos</nombreEq>
        <competiciones>
            <competicion>ligaCatalana</competicion>
        </competiciones>
        <trabajo tipo="protegerUniverso"/>
        <exitos>
            <anyos>
                <anyo num="1995">
                    <resultado igual="fracaso"/>
                    <resultado igual="fracaso"/>
                </anyo>
                <anyo num="1996">
                    <resultado igual="exito"/>
                    <resultado igual="exito"/>
                    <resultado igual="exito"/>
                </anyo>
            </anyos>
        </exitos>
        <integrantes>
            <integrante nacionalidad="francesa"> <!--nacionalidad="francesa" -->
                <nombre>he</nombre>
                <apellido>man</apellido>
                <cargo>heroe</cargo>
                <fechaNac>1983-01-01</fechaNac>
                <rutaImg extension="jpg">c:/olakase</rutaImg>
                <ultHoraPart>10:00:00</ultHoraPart>
                <ultFechaEmp>2015-11-05</ultFechaEmp>
                <estadisticas>
                    <golpes dados="98984"/>
                    <golpes recibidos="2"/>
                </estadisticas>
            </integrante>
            <integrante nacionalidad="marciana"> <!--nacionalidad="marciana" -->
                <nombre>dun</nombre>
                <apellido>can</apellido>
                <cargo>maestro armas</cargo>
                <fechaNac>1983-01-02</fechaNac>
                <ultHoraPart>18:00:00</ultHoraPart>
                <ultFechaEmp>2017-06-03</ultFechaEmp>
                <estadisticas>
                    <goles marcados="100"/>
                    <minions eliminados="50"/>
                </estadisticas>
            </integrante>
        </integrantes>
    </equipo>
</equipos>
