=== EduCaballero/LLMM/practica15_XSD/4.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    <xs:element name="sms">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="from">
                    <xs:complexType mixed="true">
                        <xs:sequence>
                            <xs:element name="nombre">
                                <xs:complexType  mixed="true">                                
                                    <xs:attribute name="telef" use="required" type="xs:string"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="to">
                    <xs:complexType mixed="true">
                        <xs:sequence>
                            <xs:element name="nombre" maxOccurs="unbounded">                                
                                <xs:complexType  mixed="true">
                                    <xs:attribute name="telef" use="required" type="xs:string"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="longitud" type="xs:integer"/>  
                <xs:element name="fecha" type="xs:date"/>                  
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== EduCaballero/LLMM/practica15_XSD/4.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<sms xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
 xsi:noNamespaceSchemaLocation="4.xsd">
    <from>
        <nombre telef="661560834">Antonio</nombre>
    </from>
    <to>
        <nombre telef="661560835">Carlos</nombre>
        <nombre telef="661560836">Merche</nombre>
    </to>
    <longitud>100</longitud>
    <fecha>2002-09-24</fecha>
</sms>
